

/*FAGERSTROM TEST FOR NICOTINE DEPENDENCE(FND)*/
/*YUE PAN 03/29/2021 */



/*CTN51*/
/*FAGERSTROM TEST FOR NICOTINE DEPENDENCE(FND)*/
/*FORMAT CIG_DAY*/
PROC FORMAT ;
	VALUE $ CIG_DAY_ 
	0="10 OR LESS"
	1="11-20"
	2="21-30"
	3="31 OR MORE";
RUN;

/*SELECT SMOKING AND NUMBER CIGS PER DAY FROM CTN51*/
PROC SQL;
   CREATE TABLE FND_01 AS 
   SELECT 
		  "51" AS PROJECT,
          T1.PATID AS WHO, 
          T1.SITE, 
		input(t1.FNSMOKE, 8.) as FNSMOKE_0,
		input(t1.FNFIRST, 8.) as FNFIRST_0,
		input(t1.FNFORBDN, 8.) as FNFORBDN_0,
		input(t1.FNGIVEUP, 8.) as FNGIVEUP_0,
		input(t1.FNNODAY, 8.) as FNNODAY_0,
		input(t1.FNFREQ, 8.) as FNFREQ_0,
		input(t1.FNSICK, 8.) as FNSICK_0,
        calculated FNFIRST_0+ calculated FNFORBDN_0+ calculated FNGIVEUP_0
           +calculated FNNODAY_0+calculated FNFREQ_0+calculated FNSICK_0 as FND,
		  /*DO YOU CURRENTLY SMOKE CIGARETTES?*/
          INPUT(T1.FNSMOKE, 8.) AS ISSMOKE, 
		  /*HOW MANY CIGARETTES/DAY DO YOU SMOKE? MISSING IS 0*/
          T1.FNNODAY AS CIG_DAY FORMAT=$CIG_DAY_.  
      FROM CTN51.FND T1;
QUIT;


PROC FREQ DATA=FND_01;
/*TABLES ISSMOKE CIG_DAY;*/
RUN;


/*CTN30*/
/*NICOTINE FROM ASI-LITE (T_FRASL4)*/
/*NICOTINE (TOBACCO PRODUCTS) FROM PAST 30 DAYS (DAYS) AND LIFE TIME (YEARS)*/
/*THERE ARE ALSO FOLLOW UP BUT NOT PULLED SINCE CAN NOT HARMONIZED*/

PROC SQL;
   CREATE TABLE FND_30_01 AS 
   SELECT "30" AS PROJECT,
		  T1.PATIENTNUMBER AS WHO, 
          CASE WHEN T1.D36A = 0 THEN 0 
	           WHEN T1.D36A > 0 THEN 1
			   ELSE . END AS ISSMOKE
/*          T1.D36B*/
      FROM CTN30.T_FRASL4 T1;
QUIT;

PROC FREQ DATA=FND_30_01;
TABLES ISSMOKE;
RUN;


/*NONE FOR CTN27*/

/*COMBINE CTN51 AND CTN30*/

DATA FND(DROP=CIG_DAY SITE);
SET FND_01 (keep= PROJECT	WHO	SITE	FND	ISSMOKE)
    FND_30_01;
RUN;

PROC FREQ DATA=FND ;
TABLES PROJECT*(fnd ISSMOKE)/MISSING;
RUN;